### ISSUE TITLE
test

### ISSUE THREAD

**Issue by louis-clotman** [louis-clotman/test#1]
[terraform-certified.pdf](https://github.com/louis-clotman/test/files/10104587/terraform-certified.pdf)

**Comment by louis-clotman** [comment]
```
                                                                                                                                                                                                                                                                                                                                                                                                 utf-8  unix  lua  Top    1:1
    1 local Plug = vim.fn['plug#']
    2
    3 vim.call('plug#begin', '~/.config/nvim/plugins')
    4 Plug 'tpope/vim-surround'
    5 Plug 'nvim-lualine/lualine.nvim'
    6 Plug('junegunn/fzf', {['do'] = './install --bin' })
    7 Plug 'junegunn/fzf.vim'
    8 Plug('neoclide/coc.nvim', {branch = 'release'})
    9 Plug('lewis6991/gitsigns.nvim', {tag = 'release'})
   10 Plug 'kyazdani42/nvim-web-devicons'
   11 Plug 'folke/trouble.nvim'
▌  12 Plug 'neovim/nvim-lspconfig'
▌  13 Plug('nvim-treesitter/nvim-treesitter', {['do'] = ':TSUpdate'})
▌  14 Plug 'jvirtanen/vim-hcl'
   15 vim.call('plug#end')
   16
▌  17 vim.keymap.set("n", "<Space>", "<Nop>", { silent = true, remap = false })
▌  18 vim.g.mapleader = " "
   19
   20 vim.opt.expandtab       = true
   21 vim.opt.shiftwidth      = 2
   22 vim.opt.tabstop         = 2
   23 vim.opt.softtabstop     = 2
   24 vim.opt.smartindent     = true
   25 vim.opt.wrap            = true
   26 vim.wo.signcolumn       = "yes"
   27 vim.opt.shell           = "/bin/zsh"
   28 vim.opt.showmode        = false
   29 vim.opt.number          = true
   30 vim.opt.updatetime      = 300
   31
   32 vim.api.nvim_set_hl(0, 'Comment', { cterm = { italic = true }, ctermfg = "Red" })
▌  33 --- vim.api.nvim_set_hl(0, 'Constant', { cterm = { italic = true }, ctermfg = "DarkBlue" })
▌  34 --- vim.api.nvim_set_hl(0, 'Statement', { cterm = { italic = true }, ctermfg = "Yellow"  })
▌  35 --- vim.api.nvim_set_hl(0, 'Identifier', { cterm = { italic = true }, ctermfg = "Magenta" })
▌  36 --- vim.api.nvim_set_hl(0, 'Keyword', { cterm = { italic = true }, ctermfg = "Yellow" })
▌  37 --- vim.api.nvim_set_hl(0, 'Conditional', { cterm = { italic = true }, ctermfg = "Green" })
▌  38 --- vim.api.nvim_set_hl(0, 'Repeat', { cterm = { italic = true }, ctermfg = "Green" })
▌  39 --- vim.api.nvim_set_hl(0, 'Label', { cterm = { italic = true }, ctermfg = "Green" })
▌  40 --- vim.api.nvim_set_hl(0, 'Number', { cterm = { italic = true }, ctermfg = "Green" })
   41 vim.api.nvim_set_hl(0, 'SignColumn', { ctermfg = "Black" })
▌  42 --- vim.api.nvim_set_hl(0, 'Folded', { ctermbg = "Black", ctermfg = "Magenta" })
▌  43 --- vim.api.nvim_set_hl(0, 'LineNr', { ctermbg = "Black", ctermfg = 237 })
   44
▌  45 local keymap = vim.api.nvim_set_keymap
▌  46 local default_opts = { noremap = true, silent = true }
▌  47 keymap("n", "<leader>ti", ":!terraform init<CR>", default_opts)
▌  48 keymap("n", "<leader>tv", ":!terraform validate<CR>", default_opts)
▌  49 keymap("n", "<leader>tp", ":!terraform plan<CR>", default_opts)
▌  50 keymap("n", "<leader>taa", ":!terraform apply -auto-approve<CR>", default_opts)
   51
   52 --------------------------------------
   53 ---    C O C
   54 --------------------------------------
   55
   56 local keyset = vim.keymap.set
   57 -- Auto complete
   58 function _G.check_back_space()
   59     local col = vim.fn.col('.') - 1
   60     return col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') ~= nil
   61 end
   62
   63 -- Use tab for trigger completion with characters ahead and navigate.
   64 -- NOTE: There's always complete item selected by default, you may want to enable
   65 -- no select by `"suggest.noselect": true` in your configuration file.
   66 -- NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
   67 -- other plugin before putting this into your config.
   68 local opts = {silent = true, noremap = true, expr = true, replace_keycodes = false}
   69 keyset("i", "<TAB>", 'coc#pum#visible() ? coc#pum#next(1) : v:lua.check_back_space() ? "<TAB>" : coc#refresh()', opts)
   70 keyset("i", "<S-TAB>", [[coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"]], opts)
   71
   72 -- Make <CR> to accept selected completion item or notify coc.nvim to format
   73 -- <C-g>u breaks current undo, please make your own choice.
   74 keyset("i", "<cr>", [[coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"]], opts)
   75
   76 -- Use <c-j> to trigger snippets
   77 keyset("i", "<c-j>", "<Plug>(coc-snippets-expand-jump)")
   78 -- Use <c-space> to trigger completion.
   79 keyset("i", "<c-space>", "coc#refresh()", {silent = true, expr = true})
   80
   81 -- Use `[g` and `]g` to navigate diagnostics
   82 -- Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
   83 keyset("n", "[g", "<Plug>(coc-diagnostic-prev)", {silent = true})
   84 keyset("n", "]g", "<Plug>(coc-diagnostic-next)", {silent = true})
   85
   86 -- GoTo code navigation.
   87 keyset("n", "gd", "<Plug>(coc-definition)", {silent = true})
   88 keyset("n", "gy", "<Plug>(coc-type-definition)", {silent = true})
   89 keyset("n", "gi", "<Plug>(coc-implementation)", {silent = true})
   90 keyset("n", "gr", "<Plug>(coc-references)", {silent = true})
   91
   92 -- Use K to show documentation in preview window.
   93 function _G.show_docs()
   94     local cw = vim.fn.expand('<cword>')
   95     if vim.fn.index({'vim', 'help'}, vim.bo.filetype) >= 0 then
   96         vim.api.nvim_command('h ' .. cw)
   97     elseif vim.api.nvim_eval('coc#rpc#ready()') then
   98         vim.fn.CocActionAsync('doHover')
   99     else
  100         vim.api.nvim_command('!' .. vim.o.keywordprg .. ' ' .. cw)
  101     end
  102 end
  103 keyset("n", "K", '<CMD>lua _G.show_docs()<CR>', {silent = true})
  104
▌ 105 -- Highlight the symbol and its references when holding the cursor.
▌ 106 vim.api.nvim_create_augroup("CocGroup", {})
▌ 107 -- vim.api.nvim_create_autocmd("CursorHold", {
▌ 108 --     group = "CocGroup",
▌ 109 --     command = "silent call CocActionAsync('highlight')",
▌ 110 --     desc = "Highlight symbol under cursor on CursorHold"
▌ 111 -- })
▌ 112
▌ 113 -- Symbol renaming.
▌ 114 keyset("n", "<leader>rn", "<Plug>(coc-rename)", {silent = true})
▌ 115
▌ 116 -- Formatting selected code.
▌ 117 keyset("x", "<leader>f", "<Plug>(coc-format-selected)", {silent = true})
▌ 118 keyset("n", "<leader>f", "<Plug>(coc-format-selected)", {silent = true})
▌ 119
▌ 120 -- Setup formatexpr specified filetype(s).
▌ 121 vim.api.nvim_create_autocmd("FileType", {
▌ 122     group = "CocGroup",
▌ 123     pattern = "typescript,json",
▌ 124     command = "setl formatexpr=CocAction('formatSelected')",
▌ 125     desc = "Setup formatexpr specified filetype(s)."
▌ 126 })
▌ 127
▌ 128 -- Update signature help on jump placeholder.
▌ 129 vim.api.nvim_create_autocmd("User", {
▌ 130     group = "CocGroup",
▌ 131     pattern = "CocJumpPlaceholder",
▌ 132     command = "call CocActionAsync('showSignatureHelp')",
▌ 133     desc = "Update signature help on jump placeholder"
▌ 134 })
▌ 135
▌ 136 -- Applying codeAction to the selected region.
▌ 137 -- Example: `<leader>aap` for current paragraph
▌ 138 keyset("x", "<leader>a", "<Plug>(coc-codeaction-selected)", opts)
▌ 139 keyset("n", "<leader>a", "<Plug>(coc-codeaction-selected)", opts)
▌ 140
▌ 141 -- Remap keys for applying codeAction to the current buffer.
▌ 142 keyset("n", "<leader>ac", "<Plug>(coc-codeaction)", opts)
▌ 143
▌ 144
▌ 145 -- Apply AutoFix to problem on the current line.
▌ 146 keyset("n", "<leader>qf", "<Plug>(coc-fix-current)", opts)
▌ 147
▌ 148
▌ 149 -- Run the Code Lens action on the current line.
▌ 150 keyset("n", "<leader>cl", "<Plug>(coc-codelens-action)", opts)
▌ 151
▌ 152
▌ 153 -- Map function and class text objects
▌ 154 -- NOTE: Requires 'textDocument.documentSymbol' support from the language server.
▌ 155 keyset("x", "if", "<Plug>(coc-funcobj-i)", opts)
▌ 156 keyset("o", "if", "<Plug>(coc-funcobj-i)", opts)
▌ 157 keyset("x", "af", "<Plug>(coc-funcobj-a)", opts)
▌ 158 keyset("o", "af", "<Plug>(coc-funcobj-a)", opts)
▌ 159 keyset("x", "ic", "<Plug>(coc-classobj-i)", opts)
▌ 160 keyset("o", "ic", "<Plug>(coc-classobj-i)", opts)
▌ 161 keyset("x", "ac", "<Plug>(coc-classobj-a)", opts)
▌ 162 keyset("o", "ac", "<Plug>(coc-classobj-a)", opts)
▌ 163
▌ 164
▌ 165 -- Remap <C-f> and <C-b> for scroll float windows/popups.
▌ 166 ---@diagnostic disable-next-line: redefined-local
▌ 167 keyset("n", "<C-f>", 'coc#float#has_scroll() ? coc#float#scroll(1) : "<C-f>"', opts)
▌ 168 keyset("n", "<C-b>", 'coc#float#has_scroll() ? coc#float#scroll(0) : "<C-b>"', opts)
▌ 169 keyset("i", "<C-f>",
▌ 170        'coc#float#has_scroll() ? "<c-r>=coc#float#scroll(1)<cr>" : "<Right>"', opts)
▌ 171 keyset("i", "<C-b>",
▌ 172        'coc#float#has_scroll() ? "<c-r>=coc#float#scroll(0)<cr>" : "<Left>"', opts)
▌ 173 keyset("v", "<C-f>", 'coc#float#has_scroll() ? coc#float#scroll(1) : "<C-f>"', opts)
▌ 174 keyset("v", "<C-b>", 'coc#float#has_scroll() ? coc#float#scroll(0) : "<C-b>"', opts)
▌ 175
▌ 176
▌ 177 -- Use CTRL-S for selections ranges.
▌ 178 -- Requires 'textDocument/selectionRange' support of language server.
▌ 179 keyset("n", "<C-s>", "<Plug>(coc-range-select)", {silent = true})
▌ 180 keyset("x", "<C-s>", "<Plug>(coc-range-select)", {silent = true})
▌ 181
▌ 182
▌ 183 -- Add `:Format` command to format current buffer.
▌ 184 vim.api.nvim_create_user_command("Format", "call CocAction('format')", {})
▌ 185
▌ 186 -- " Add `:Fold` command to fold current buffer.
▌ 187 vim.api.nvim_create_user_command("Fold", "call CocAction('fold', <f-args>)", {nargs = '?'})
▌ 188
▌ 189 -- Add `:OR` command for organize imports of the current buffer.
▌ 190 vim.api.nvim_create_user_command("OR", "call CocActionAsync('runCommand', 'editor.action.organizeImport')", {})
▌ 191
▌ 192 -- Add (Neo)Vim's native statusline support.
▌ 193 -- NOTE: Please see `:h coc-status` for integrations with external plugins that
▌ 194 -- provide custom statusline: lightline.vim, vim-airline.
▌ 195 vim.opt.statusline:prepend("%{coc#status()}%{get(b:,'coc_current_function','')}")
▌ 196
▌ 197 -- Mappings for CoCList
▌ 198 -- code actions and coc stuff
▌ 199 ---@diagnostic disable-next-line: redefined-local
▌ 200 -- Show all diagnostics.
▌ 201 keyset("n", "<space>a", ":<C-u>CocList diagnostics<cr>", opts)
▌ 202 -- Manage extensions.
▌ 203 keyset("n", "<space>e", ":<C-u>CocList extensions<cr>", opts)
▌ 204 -- Show commands.
▌ 205 keyset("n", "<space>c", ":<C-u>CocList commands<cr>", opts)
▌ 206 -- Find symbol of current document.
▌ 207 keyset("n", "<space>o", ":<C-u>CocList outline<cr>", opts)
▌ 208 -- Search workspace symbols.
▌ 209 keyset("n", "<space>s", ":<C-u>CocList -I symbols<cr>", opts)
▌ 210 -- Do default action for next item.
▌ 211 keyset("n", "<space>j", ":<C-u>CocNext<cr>", opts)
▌ 212 -- Do default action for previous item.
▌ 213 keyset("n", "<space>k", ":<C-u>CocPrev<cr>", opts)
▌ 214 -- Resume latest coc list.
▌ 215 keyset("n", "<space>p", ":<C-u>CocListResume<cr>", opts)
▌ 216
▌ 217
  218 --------------------------------------
  219 ---    L U A L I N E
  220 --------------------------------------
  221
  222 require('lualine').setup {
  223   options = {
  224     icons_enabled = false,
  225     theme = '16color',
  226     component_separators = { left = '', right = ''},
  227     section_separators = { left = '', right = ''},
  228     disabled_filetypes = {
  229       statusline = {},
  230       winbar = {},
  231     },
  232     ignore_focus = {},
  233     always_divide_middle = true,
  234     globalstatus = false,
  235     refresh = {
  236       statusline = 1000,
  237       tabline = 1000,
  238       winbar = 1000,
  239     }
  240   },
  241   sections = {
  242     lualine_a = {'mode'},
  243     lualine_b = {'branch', 'diff', 'diagnostics'},
  244     lualine_c = {'filename'},
  245     lualine_x = {'encoding', 'fileformat', 'filetype'},
  246     lualine_y = {'progress'},
  247     lualine_z = {'location'}
  248   },
  249   inactive_sections = {
  250     lualine_a = {},
  251     lualine_b = {},
  252     lualine_c = {'filename'},
  253     lualine_x = {'location'},
  254     lualine_y = {},
  255     lualine_z = {}
  256   },
  257   tabline = {},
  258   winbar = {},
  259   inactive_winbar = {},
  260   extensions = {}
  261 }
  262
  263 vim.api.nvim_create_autocmd({ "BufWritePre" }, {
  264   pattern = { "*" },
  265   command = [[%s/\s\+$//e]],
  266 })
  267
  268
▌ 269 --------------------------------------
▌ 270 ---    T E R R A F O R M
▌ 271 --------------------------------------
▌ 272
▌ 273 require'lspconfig'.tflint.setup{}
▌ 274 require'lspconfig'.terraformls.setup{}
▌ 275 vim.api.nvim_create_autocmd({"BufWritePre"}, {
▌ 276   pattern = {"*.tf", "*.tfvars"},
▌ 277   callback = vim.lsp.buf.formatting_sync,
▌ 278 })
▌ 279
▌ 280
│ 281 --------------------------------------
  282 ---    G I T S I G N S
  283 --------------------------------------
  284
  285 require('gitsigns').setup {
  286   signs = {
  287     add          = {hl = 'GitSignsAdd'   , text = '│', numhl='GitSignsAddNr'   , linehl='GitSignsAddLn'},
  288     change       = {hl = 'GitSignsChange', text = '│', numhl='GitSignsChangeNr', linehl='GitSignsChangeLn'},
  289     delete       = {hl = 'GitSignsDelete', text = '_', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn'},
  290     topdelete    = {hl = 'GitSignsDelete', text = '‾', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn'},
  291     changedelete = {hl = 'GitSignsChange', text = '~', numhl='GitSignsChangeNr', linehl='GitSignsChangeLn'},
  292   },
  293   signcolumn = true,  -- Toggle with `:Gitsigns toggle_signs`
  294   numhl      = false, -- Toggle with `:Gitsigns toggle_numhl`
  295   linehl     = false, -- Toggle with `:Gitsigns toggle_linehl`
  296   word_diff  = false, -- Toggle with `:Gitsigns toggle_word_diff`
  297   watch_gitdir = {
  298     interval = 1000,
  299     follow_files = true
  300   },
  301   attach_to_untracked = true,
  302   current_line_blame = false, -- Toggle with `:Gitsigns toggle_current_line_blame`
  303   current_line_blame_opts = {
  304     virt_text = true,
  305     virt_text_pos = 'eol', -- 'eol' | 'overlay' | 'right_align'
  306     delay = 1000,
  307     ignore_whitespace = false,
  308   },
  309   current_line_blame_formatter = '<author>, <author_time:%Y-%m-%d> - <summary>',
  310   sign_priority = 6,
  311   update_debounce = 100,
  312   status_formatter = nil, -- Use default
  313   max_file_length = 40000, -- Disable if file is longer than this (in lines)
  314   preview_config = {
  315     -- Options passed to nvim_open_win
  316     border = 'single',
  317     style = 'minimal',
  318     relative = 'cursor',
  319     row = 0,
  320     col = 1
  321   },
  322   yadm = {
  323     enable = false
  324   },
  325
  326   on_attach = function(bufnr)
  327     local gs = package.loaded.gitsigns
  328
 329     local function map(mode, l, r, opts)
  330       opts = opts or {}
  331       opts.buffer = bufnr
  332       vim.keymap.set(mode, l, r, opts)
  333     end
  334
  335     -- Navigation
  336     map('n', ']c', function()
  337       if vim.wo.diff then return ']c' end
  338       vim.schedule(function() gs.next_hunk() end)
  339       return '<Ignore>'
  340     end, {expr=true})
  341
  342     map('n', '[c', function()
  343       if vim.wo.diff then return '[c' end
  344       vim.schedule(function() gs.prev_hunk() end)
  345       return '<Ignore>'
  346     end, {expr=true})
  347
  348     -- Actions
  349     map({'n', 'v'}, '<leader>hs', ':Gitsigns stage_hunk<CR>')
  350     map({'n', 'v'}, '<leader>hr', ':Gitsigns reset_hunk<CR>')
  351     map('n', '<leader>hS', gs.stage_buffer)
  352     map('n', '<leader>hu', gs.undo_stage_hunk)
  353     map('n', '<leader>hR', gs.reset_buffer)
  354     map('n', '<leader>hp', gs.preview_hunk)
  355     map('n', '<leader>hb', function() gs.blame_line{full=true} end)
  356     map('n', '<leader>tb', gs.toggle_current_line_blame)
  357     map('n', '<leader>hd', gs.diffthis)
  358     map('n', '<leader>hD', function() gs.diffthis('~') end)
  359     map('n', '<leader>td', gs.toggle_deleted)
  360
  361     -- Text object
  362     map({'o', 'x'}, 'ih', ':<C-U>Gitsigns select_hunk<CR>')
  363   end
  364 }
~
```

**Comment by louis-clotman** [comment]
```
variable "lambdas_in_s3" {
  type = map(object({
    architecture  = optional(string, "x86_64")
    description   = optional(string)
    memory_size   = optional(number, 120)
    timeout       = optional(number, 3)
    env_vars      = optional(map)
  }))
}
```

**Comment by louis-clotman** [comment]
[terraform-aws-lambda.zip](https://github.com/louis-clotman/test/files/10150773/terraform-aws-lambda.zip)
zip

**Comment by louis-clotman** [comment]
[lambda_ecr.zip](https://github.com/louis-clotman/test/files/10150855/lambda_ecr.zip)
w

**Comment by louis-clotman** [comment]
``
FROM public.ecr.aws/lambda/python:3.9

# Install the function's dependencies using file requirements.txt
# from your project folder.

# COPY requirements.txt  .
# RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY glue_trigger.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "glue_trigger.lambda_handler" ] 
```

**Comment by louis-clotman** [comment]
```
FROM public.ecr.aws/lambda/python:3.9

# Install the function's dependencies using file requirements.txt
# from your project folder.

# COPY requirements.txt  .
# RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY glue_trigger.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "glue_trigger.lambda_handler" ] 
```

**Comment by louis-clotman** [comment]
glue trigger
```
# Set up logging
import json
import os
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
# Import Boto 3 for AWS Glue
import boto3


# Variables for the job: 


def getPayload(bkt,key):
    """
    Read S3 object returns the payload frame.
    """
    try:
        s3 = boto3.resource('s3')
        obj = s3.Object(bucket_name=bkt, key=key)
        data=obj.get()['Body'].read().decode('ascii')
        return data
    except Exception as e:
        logger.error("Received exception in Reading the file {} from bucket {} and exeception we got {}".format(key,bkt,e))
        raise e     


def trigger_glue_job(event):
    """
    This function triggers a glue and passes the input to the Job.
    """
    try:
        logger.info('## Creating the Glue Client')
        client = boto3.client('glue')
        glueJobName = event.get("GLUEJOBNAME")
        payload=getPayload(event.get("PAYLOADBUCKET"),event.get("PAYLOADFILE"))
        driver=event.get("DRIVERTYPE")
        response = client.start_job_run(JobName = glueJobName,
        Arguments = {
                 '--continuous-log-logGroup':   glueJobName,
                 '--enable-continuous-log-filter':  'true',
                 '--payload':  payload,
                 '--driver': driver,
                 '--enable-auto-scaling':'true' } 
                 )
        logger.info('## STARTED GLUE JOB: ' + glueJobName)
        return response
    except Exception as e:
        logger.error("Received exception in trigger Glue Job {}".format(e))
        raise e



# Define Lambda function
def lambda_handler(event, context):
    """
    Entry point method. This takes input from event and executes the glue JOb.
    """
    try:
        logger.info("============================================================================================================ ")
        logger.info("Input from the Payload:{}".format(event))
        logger.info("============================================================================================================ ")
        response=trigger_glue_job(event)
        logger.info('## GLUE JOB RUN ID: ' + response['JobRunId'])
        return response['JobRunId']
    except Exception as e:
        logger.error("Received exception while executing the lambda handler : {}".format(e))
        raise e  
```

**Comment by louis-clotman** [comment]
lz glue trigger

```
# Set up logging
import json
import os
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
# Import Boto 3 for AWS Glue
import boto3


# Variables for the job: 


def getPayload(bkt,key):
    """
    Read S3 object returns the payload frame.
    """
    try:
        s3 = boto3.resource('s3')
        obj = s3.Object(bucket_name=bkt, key=key)
        data=obj.get()['Body'].read().decode('ascii')
        return data
    except Exception as e:
        logger.error("Received exception in Reding the file {} from bucket {} and exeception we got {}".format(key,bkt,e))
    raise e     


def trigger_glue_job(event):
    """
    This function triggers a glue and passes the input to the Job.
    """
    try:
        logger.info('## Creating the STS Client')
        client = boto3.client(
            'sts',
             region_name="us-east-1",
            endpoint_url="https://sts.us-east-1.amazonaws.com"
        )
        print(client)
        logger.info('## STS Client is created')
        response = client.get_caller_identity()
        print(response)
        acct_lz = client.assume_role(
            RoleArn="arn:aws:iam::489678179331:role/lz.lambda-service.role",
            RoleSessionName="cross_acct_glue",
            DurationSeconds=900
        )
        
        ACCESS_KEY = acct_lz['Credentials']['AccessKeyId']
        SECRET_KEY = acct_lz['Credentials']['SecretAccessKey']
        SESSION_TOKEN = acct_lz['Credentials']['SessionToken']
        
        logger.info("STS Successfully completed {},{},{}".format(ACCESS_KEY,SECRET_KEY,SESSION_TOKEN))
        
        logger.info('## Creating the Glue Client')
        # create service client using the assumed role credentials, e.g. S3
        client = boto3.client(
            'glue',
            aws_access_key_id=ACCESS_KEY,
            aws_secret_access_key=SECRET_KEY,
            aws_session_token=SESSION_TOKEN
        )
        glueJobName = event.get("GLUEJOBNAME")
        payload=getPayload(event.get("PAYLOADBUCKET"),event.get("PAYLOADFILE"))
        driver=event.get("DRIVERTYPE")
        response = client.start_job_run(JobName = glueJobName,
        Arguments = {
                 '--continuous-log-logGroup':   glueJobName,
                 '--enable-continuous-log-filter':  'true',
                 '--payload':  payload,
                 '--driver': driver,
                 '--enable-auto-scaling':'true' } 
                 )
        logger.info('## STARTED GLUE JOB: ' + glueJobName)
        return response
    except Exception as e:
        logger.error("Received exception in trigger Glue Job {}".format(e))
    raise e 



# Define Lambda function
def lambda_handler(event, context):
    """
    Entry point method. This takes input from event and executes the glue JOb.
    """
    try:
        logger.info("============================================================================================================ ")
        logger.info("Input from the Payload:{}".format(event))
        logger.info("============================================================================================================ ")
        response=trigger_glue_job(event)
        logger.info('## GLUE JOB RUN ID: ' + response['JobRunId'])
        return response['JobRunId']
    except Exception as e:
        logger.error("Received exception while executing the lambda handler : {}".format(e))
        raise e  
```

**Comment by louis-clotman** [comment]
launch_ec2
```
import boto3 
import logging
import os


logger = logging.getLogger()
logger.setLevel(logging.INFO)

def call_ec2(event):
    """
    Creates the EC2 from the specification from the event
    """
    try:
        REGION = event.get("REGION")
        AMI = event.get("AMI")
        INSTANCE_TYPE = event.get("INSTANCETYPE")
        BUCKET = event.get("BUCKET")
        SCRIPT_PATH = event.get("SCRIPTPATH")
        SECURITYGROUPID = event.get("SECURITYGROUPID").split(",")
        SUBNETID = event.get("SUBNETID")
        IAM = event.get("IAM")
        
        
        LOCAL_SCRIPT_PATH='/tmp/ec2_bootstrap.sh'
        listOfDir = os.listdir( '/tmp/' )
        logger.info("list of dirs : {}".format(listOfDir))

        EC2 = boto3.client('ec2', region_name=REGION)
        S3 = boto3.client('s3', region_name=REGION)

        S3.download_file(BUCKET, SCRIPT_PATH, LOCAL_SCRIPT_PATH)
        logger.info("Files Downloaded successfuly")
        listOfDir = os.listdir( '/tmp/' )
        logger.info("list of dirs : {}".format(listOfDir))
        with open(LOCAL_SCRIPT_PATH, 'r') as f:
            script = '\n'.join(f)
            EC2.run_instances(
                ImageId=AMI,
                InstanceType=INSTANCE_TYPE,
                MinCount=1,
                MaxCount=1,
                InstanceInitiatedShutdownBehavior='terminate',
                UserData=script,
                SecurityGroupIds=SECURITYGROUPID,
                SubnetId=SUBNETID,
                IamInstanceProfile={"Arn": IAM}
            )
            return 'success'
    except Exception as e:
        logger.error("Received exception in ec2 call function: {}".format(e))
        raise e            
    


def lambda_handler(event, context):
  """
  Lambda Handler to parses the event and calls the status of the emr
  """
  try:
    status=call_ec2(event)
  
    return status
  
  except Exception as e:
    logger.error("Received exception in lambda handler: {}".format(e))
    raise e 

```

**Comment by louis-clotman** [comment]
dockerfile
```
FROM public.ecr.aws/lambda/python:3.9

# Install the function's dependencies using file requirements.txt
# from your project folder.

# COPY requirements.txt  .
# RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY launch_ec2.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "launch_ec2.lambda_handler" ] 
```

**Comment by louis-clotman** [comment]
Producer
```
│ Error: Failed to download module
│ 
│ Could not download module "ip_glue_trigger" (lambda.tf:5) source code from
│ "git::https://bitbucketp.duke-energy.com/scm/AWSIP/innovation-platform-aws-infrastructure.git?ref=feature/sbx":
│ error downloading
│ 'https://bitbucketp.duke-energy.com/scm/AWSIP/innovation-platform-aws-infrastructure.git?ref=feature%2Fsbx':
│ /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/ip_glue_trigger'...
│ fatal: could not read Username for 'https://bitbucketp.duke-energy.com': No
│ such device or address
```

**Comment by louis-clotman** [comment]
Consumer
```
CONSUMER_AWS_ACCOUNT: '185922140488'
CONSUMER_IAM_ROLES_FOR_ACCESS:
  # - ROLE_ARN: 'arn:aws:iam::044591612525:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_data-engineer.044591612525_56cbcdfec1c32a8b'
  #   ACCESS_TYPE: read # *CHANGE ME* with values read or write
  - ROLE_ARN: 'arn:aws:iam::185922140488:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_developer_b5f974e89fad755c' ## ADD CONSUMER SSO
    ACCESS_TYPE: write # *CHANGE ME* with values read or write
DATABASE_TAGS_FOR_ACCESS:
    - DATABASE_NAME: sbxacct_curr # *CHANGE ME* this value is name of the database
      TAGS:
        product-innovation-sbx-acct: allow # *CHANGE ME* this is the key and value of the tag to associtate
    - DATABASE_NAME: sbxacct_publish  # *CHANGE ME* this value is name of the database
      TAGS:
        product-innovation-sbx-acct: allow  # *CHANGE ME* this is the key and value of the tag to associtate
    - DATABASE_NAME: lzacct_custodian  # *CHANGE ME* this value is name of the database
      TAGS:
        product-innovation-acc-1: allow  # *CHANGE ME* this is the key and value of the tag to associtate
DATABASE_ENTERPRISE_TAGS_FOR_ACCESS:
    - DATABASE_NAME: sbxacct_curr ## *CHANGE ME* this key is name of the database
      TAGS: 
        DOMAIN: common # *CHANGE ME* this value of the tag to
        SECURITY-CLASSIFICATION: confidential # *CHANGE ME* this value of the tag to
        DATA-PRODUCT-TYPE: bi-reporting # *CHANGE ME* this value of the tag to
    - DATABASE_NAME: sbxacct_publish
      TAGS:
        DOMAIN: common # *CHANGE ME* this value of the tag to
        SECURITY-CLASSIFICATION: confidential # *CHANGE ME* this value of the tag to
        DATA-PRODUCT-TYPE: bi-reporting # *CHANGE ME* this value of the tag to
    - DATABASE_NAME: lzacct_custodian
      TAGS:
        DOMAIN: common # *CHANGE ME* this value of the tag to
        SECURITY-CLASSIFICATION: confidential # *CHANGE ME* this value of the tag to
        DATA-PRODUCT-TYPE: bi-reporting # *CHANGE ME* this value of the tag to
################################################################################
## THE FOLLOWING SECTION IS OPTIONAL FOR INCREASED GRANULARITY AT TABLE AND COLUMN LEVEL.
## BY DEFAULT ALL TABLE TAG PERMISSIONS ARE INHERITED FROM THE DATABASE (THROUGH THE CODE- This needs to be updated in the code. concat database permissions with table permissions)
####################  #################### ####################  ####################
# TABLE_TAGS_FOR_ACCESS:
#   - DATABASE_NAME: isop
#     TABLE_NAME: isop_table
#     TAGS:
#       igrid-table-tag: foo #(only one value can be appplied)
# # TABLE_ENTERPRISE_TAGS_FOR_ACCESS:
# #   - DATABASE_NAME: isop
# #     TABLE_NAME: isop_table
# #     TAGS:
# #       - TABLE-DOMAIN: foo #(only one value can be appplied)
# COLUMN_TAGS_FOR_ACCESS: ##(in the code concat database, table and column tag permissions)
#   - DATABASE_NAME: isop
#     TABLE_NAME: isop_table
#     COLUMN_NAME: isop_column
#     TAGS:
#         igrid-column-tag: foo #(only one value can be appplied)
```
